global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "nodeapp"
    static_configs:
      - targets: ["nodeapp:3000"]

  - job_name: "elasticsearch"
    metrics_path: /_prometheus/metrics
    static_configs:
      - targets: ["elasticsearch:9200"]
